### ISSUE TITLE
Too much Violence in names of sub directories of Studies Repo

### ISSUE THREAD

**Issue by ShootingKing-AM** [warhawk3407/studies#1]
Please consider censoring some of sub-directories and java package names. Or Please tag as appropriate for 18+. And please consider spending some time on BGP.

Thanks in Advance.
Shooting King

**Comment by warhawk3407** [comment]
Well thank you for the comment, I will rebuild this repo, done this one fast.

For BGP, I will try to work on it with my school, not on my own, in order to code it as a school project.
